Repository Verus-Datum/site, pull requests merged in 2025-05, with the labels that each got.

#55 Rework API + Tests & Create register
  .devcontainer/dev.env
  .devcontainer/devcontainer.json
  .devcontainer/requirements.in
  .devcontainer/requirements.txt
  .github/workflows/py.yaml
  .github/workflows/registry.yml
  .gitignore
  charts/vd/values.yaml
  compose.yml
  deploy/api/Dockerfile
  deploy/api/requirements.in
  deploy/api/requirements.txt
  pytest.ini
  scripts/setup.sh
  scripts/update_py_deps.sh
  src/api/__init__.py
  src/api/cors.py
  src/api/db.py
  src/api/main.py
  src/api/models.py
  src/api/pyproject.toml
  src/api/routers/__init__.py
  src/api/routers/health.py
  src/api/routers/listings.py
  src/api/routers/users.py
  src/api/schemas.py
  src/api/tests/__init__.py
  src/api/tests/conftest.py
  src/api/tests/test_routers.py
  src/web/package-lock.json
  src/web/package.json
  src/web/src/components/business/BusinessMarker.svelte
  src/web/src/components/layout/Map.svelte
  src/web/src/components/layout/Navbar.svelte
  src/web/src/components/ui/form/index.ts
  src/web/src/components/user/AuthProvider.svelte
  src/web/src/components/user/UserDropdown.svelte
  src/web/src/routes/+layout.svelte
  src/web/src/routes/login/+page.server.ts
  src/web/src/routes/login/+page.svelte
  src/web/src/routes/login/schema.ts
  src/web/src/routes/profile/+page.svelte
  src/web/src/routes/register/+page.server.ts
  src/web/src/routes/register/+page.svelte
  src/web/src/routes/register/schema.ts
  src/web/src/states/CurrentUser.svelte.ts
  src/web/src/states/MapState.svelte.ts
  src/web/src/types/AuthUser.ts
  src/web/src/types/Business.ts
  src/web/src/types/User.ts
  src/web/src/utils/api.ts
  src/web/src/utils/firebase.ts
Labels: Ready for Review

#71 Online browsing page
  src/web/src/components/business/BusinessMarker.svelte
  src/web/src/components/business/ListingCard.svelte
  src/web/src/components/business/OnlineListing.svelte
  src/web/src/components/layout/Navbar.svelte
  src/web/src/components/ui/select/select-trigger.svelte
  src/web/src/routes/listings/online/+page.svelte
  src/web/src/types/Business.ts
  src/web/src/utils/markets.ts
  src/web/tailwind.config.ts
Labels: web, Ready for Review

#76 everything is from /api now
  src/api/cors.py
  src/api/main.py
  src/api/pyproject.toml
  src/web/src/utils/api.ts
Labels: Ready for Review

#83 Update minimum number of tags in registry-clean wf
  .github/workflows/registry-clean.yaml
Labels: Ready for Review

#87 86 Update CI/CD
  .github/workflows/code.yaml
  .github/workflows/registry-clean.yaml
  .github/workflows/registry.yml
Labels: Ready for Review

#105 104 Auto assign issues to project
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/default.md
Labels: Ready for Review

#108 107 Integration Tests & Update latest tag
  .github/workflows/integration.yaml
  .github/workflows/registry.yml
  compose.yml
Labels: Ready for Review

#114 Converted `/listings/online` to `/listings`
  src/web/package-lock.json
  src/web/package.json
  src/web/src/app.css
  src/web/src/components/business/OnlineListing.svelte
  src/web/src/components/layout/Navbar.svelte
  src/web/src/components/ui/select/index.ts
  src/web/src/components/ui/slider/slider.svelte
  src/web/src/components/user/UserDropdown.svelte
  src/web/src/lib/businessFilters.ts
  src/web/src/routes/+layout.svelte
  src/web/src/routes/+page.svelte
  src/web/src/routes/brokers/[id]/+page.svelte
  src/web/src/routes/listings/+page.svelte
  src/web/src/routes/listings/[id]/+page.svelte
  src/web/src/routes/listings/create/+page.svelte
  src/web/src/routes/listings/online/+page.svelte
  src/web/src/types/Business.ts
  src/web/src/utils/markets.ts
  src/web/svelte.config.js
  src/web/tsconfig.json
Labels: web

#119 fix profile page not working with infinite if statements
  src/api/main.py
  src/web/src/routes/profile/+page.svelte
  src/web/src/types/Broker.ts
Labels: web
